# Generated by Django 5.0.7 on 2024-07-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(default="default",max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='department',
            field=models.CharField(default='deafult_code', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='history',
            field=models.TextField(default='default_code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(default='default_code', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='photo',
            field=models.ImageField(default='default_code', upload_to='inventory_photos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='pic',
            field=models.CharField(default='default_code', max_length=255),
            preserve_default=False,
        ),
    ]
