# Generated by Django 5.0.7 on 2024-07-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='code',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
