# Generated by Django 5.0.7 on 2024-07-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
